steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - build
      - -t
      - gcr.io/operaciones-br/xerticaproc-api:latest
      - -f
      - backend/Dockerfile
      - .
images:
  - gcr.io/operaciones-br/xerticaproc-api:latest
